-- Exporta la ESTRUCTURA de la base (sin datos) como sentencias SQL.
-- Uso: pegar en Supabase -> SQL Editor -> Run, luego "Export" -> "Download CSV".
-- Cada fila de la columna "ddl" es una sentencia; en orden forman el esquema completo.
with parts as (
  -- Extensiones
  select 1 as ord, e.extname::text as k,
         format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname) as ddl
  from pg_extension e join pg_namespace n on n.oid = e.extnamespace
  where e.extname <> 'plpgsql'

  union all
  -- Tipos enum
  select 2, t.typname::text,
         format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
                string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder))
  from pg_type t join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public'
  group by t.typname

  union all
  -- Secuencias (no identity)
  select 3, s.relname::text, format('CREATE SEQUENCE IF NOT EXISTS public.%I;', s.relname)
  from pg_class s join pg_namespace n on n.oid = s.relnamespace
  where s.relkind = 'S' and n.nspname = 'public'
    and not exists (select 1 from pg_depend d where d.objid = s.oid and d.deptype = 'i')

  union all
  -- Tablas con columnas y restricciones (PK, UNIQUE, CHECK)
  select 4, c.relname::text,
         format(E'CREATE TABLE public.%I (\n%s\n);', c.relname, (
           select string_agg(x, E',\n' order by o) from (
             select a.attnum::bigint as o,
                    format('  %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
                    || case
                         when a.attidentity = 'a' then ' GENERATED ALWAYS AS IDENTITY'
                         when a.attidentity = 'd' then ' GENERATED BY DEFAULT AS IDENTITY'
                         when a.attgenerated = 's' then ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
                         when d.adbin is not null then ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
                         else '' end
                    || case when a.attnotnull then ' NOT NULL' else '' end as x
             from pg_attribute a
             left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
             where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
             union all
             select 100000 + row_number() over (order by k.contype, k.conname),
                    format('  CONSTRAINT %I %s', k.conname, pg_get_constraintdef(k.oid))
             from pg_constraint k
             where k.conrelid = c.oid and k.contype in ('p', 'u', 'c', 'x')
           ) q))
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p')

  union all
  -- Dueño de secuencias
  select 5, s.relname::text,
         format('ALTER SEQUENCE public.%I OWNED BY public.%I.%I;', s.relname, t.relname, a.attname)
  from pg_depend d
  join pg_class s on s.oid = d.objid and s.relkind = 'S'
  join pg_class t on t.oid = d.refobjid
  join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
  join pg_namespace n on n.oid = s.relnamespace
  where n.nspname = 'public' and d.deptype = 'a'

  union all
  -- Llaves foráneas
  select 6, c.relname || '.' || k.conname,
         format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', c.relname, k.conname, pg_get_constraintdef(k.oid))
  from pg_constraint k join pg_class c on c.oid = k.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and k.contype = 'f'

  union all
  -- Índices (los que no vienen de una restricción)
  select 7, i.tablename || '.' || i.indexname, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (select 1 from pg_constraint k
                    where k.conname = i.indexname and k.connamespace = 'public'::regnamespace)

  union all
  -- Funciones y procedimientos
  select 8, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         pg_get_functiondef(p.oid) || ';'
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')

  union all
  -- Vistas
  select 9, c.relname::text,
         format(E'CREATE %s public.%I AS\n%s',
                case when c.relkind = 'm' then 'MATERIALIZED VIEW' else 'OR REPLACE VIEW' end,
                c.relname, pg_get_viewdef(c.oid))
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('v', 'm')

  union all
  -- Triggers (en public y en auth.users que llaman funciones propias)
  select 10, n.nspname || '.' || c.relname || '.' || t.tgname, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t join pg_class c on c.oid = t.tgrelid
  join pg_namespace n on n.oid = c.relnamespace
  join pg_proc p on p.oid = t.tgfoid
  where not t.tgisinternal
    and (n.nspname = 'public' or (n.nspname = 'auth' and p.pronamespace = 'public'::regnamespace))

  union all
  -- Activar RLS
  select 11, c.relname::text, format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname)
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p') and c.relrowsecurity

  union all
  -- Buckets de storage
  select 12, b.id::text,
         format('INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types) VALUES (%L, %L, %s, %s, %s) ON CONFLICT (id) DO NOTHING;',
                b.id, b.name, b.public,
                coalesce(b.file_size_limit::text, 'NULL'),
                coalesce(quote_literal(b.allowed_mime_types::text) || '::text[]', 'NULL'))
  from storage.buckets b

  union all
  -- Políticas RLS (public y storage)
  select 13, p.schemaname || '.' || p.tablename || '.' || p.policyname,
         format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s',
                p.policyname, p.schemaname, p.tablename, p.permissive, p.cmd, array_to_string(p.roles, ', '))
         || coalesce(E'\n  USING (' || p.qual || ')', '')
         || coalesce(E'\n  WITH CHECK (' || p.with_check || ')', '')
         || ';'
  from pg_policies p
  where p.schemaname in ('public', 'storage')

  union all
  -- Permisos sobre tablas para anon / authenticated
  select 14, c.relname::text,
         format('REVOKE ALL ON TABLE public.%I FROM anon, authenticated;', c.relname)
         || coalesce((
              select string_agg(format(E'\nGRANT %s ON TABLE public.%I TO %I;', privs, c.relname, g), '')
              from (select pg_get_userbyid(a.grantee) as g, string_agg(a.privilege_type, ', ') as privs
                    from aclexplode(c.relacl) a
                    where a.grantee <> 0 and pg_get_userbyid(a.grantee) in ('anon', 'authenticated')
                    group by 1) s), '')
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p', 'v', 'm') and c.relacl is not null

  union all
  -- Permisos de ejecución de funciones
  select 15, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
         format('REVOKE ALL ON FUNCTION public.%I(%s) FROM PUBLIC;', p.proname, pg_get_function_identity_arguments(p.oid))
         || coalesce((
              select string_agg(format(E'\nGRANT EXECUTE ON FUNCTION public.%I(%s) TO %s;',
                                       p.proname, pg_get_function_identity_arguments(p.oid),
                                       case when a.grantee = 0 then 'PUBLIC' else quote_ident(pg_get_userbyid(a.grantee)) end), '')
              from aclexplode(p.proacl) a where a.privilege_type = 'EXECUTE'), '')
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.proacl is not null
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
)
select ord, k, ddl from parts order by ord, k;
